### ISSUE TITLE
sensors not showing up

### ISSUE THREAD

**Issue by aw1604** [zhbjsh/homeassistant-ssh#1]
Hello,
I tried to add a raspberry pi using homeassistant-ssh - It kinda worked, but the sensors from the default set (cpu_load, temperature, free_disk_space_) are not showing up in HA.
I'm using HA 2023.7.3 (docker install) and homeassistant-ssh (HACS install).
using the debug log it shows that the commands on the pi are successfully executed, but I also found the following traceback:

2023-08-11 11:39:24.937 DEBUG (MainThread) [custom_components.ssh] vz1: echo $(($(cat /sys/class/thermal/thermal_zone0/te
mp) / 1000)) => ['37'], [], 0
2023-08-11 11:39:24.937 DEBUG (MainThread) [custom_components.ssh] vz1: temperature => 37
2023-08-11 11:39:25.011 DEBUG (MainThread) [custom_components.ssh] vz1: ps -e | awk 'END {print NR-1}' => ['161'], [], 0
2023-08-11 11:39:25.011 DEBUG (MainThread) [custom_components.ssh] vz1: processes => 161
2023-08-11 11:39:25.025 DEBUG (MainThread) [custom_components.ssh] vz1: cat /proc/uptime | awk '{print $1}' => ['2498294.
78'], [], 0
2023-08-11 11:39:25.027 DEBUG (MainThread) [custom_components.ssh] vz1: uptime => 28
2023-08-11 11:39:25.027 DEBUG (MainThread) [custom_components.ssh] Finished fetching vz1 state data in 1.130 seconds (suc
cess: True)
2023-08-11 11:39:25.035 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ssh platform for sens
or
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/ssh/sensor.py", line 20, in async_setup_entry
    entities = await async_get_entities(hass, config_entry, entry_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ssh/helpers/sensor.py", line 46, in async_get_entities
    sensor.on_child_added.subscribe(child_added_listener)
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NumberSensor' object has no attribute 'on_child_added'

**Comment by zhbjsh** [comment]
Hi! Thanks for reporting this issue, my guess is that you downloaded the master branch from HACS when the version was not ready yet (I just realized there is this option).

Please remove the device from Home Assistant (backup the configuration to a text file first, if you made any modifications to the commands), then download the newest version 0.9.4 from HACS and add the device again.

Let me know if it works!

**Comment by zhbjsh** [comment]
Thank you for trying it out! Yea, I added this command to get some more device information to display in Home Assistant, but you can ignore the message, as the command will only execute once after connecting (or you can just delete it from the settings).
