### ISSUE TITLE
Beta 2024.6.0 gives warning messages - log attached

### ISSUE THREAD

**Issue by mhoogenbosch** [zhbjsh/homeassistant-ssh#15]
With beta of 2024.6.0 there are warning messages about blocking loop in the logs:

```
2024-06-04 17:41:24.576 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'ssh' at custom_components/ssh/__init__.py, line 123: manager = SSHManager( (offender: /usr/local/lib/python3.12/site-packages/paramiko/hostkeys.py, line 89: with open(filename, "r") as f:), please create a bug report at https://github.com/zhbjsh/homeassistant-ssh/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 188, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ssh/__init__.py", line 123, in async_setup_entry
    manager = SSHManager(

```

Full log file:
[home-assistant.zip](https://github.com/user-attachments/files/15567370/home-assistant.zip)

**Comment by zhbjsh** [comment]
Hi, thanks a lot for reporting this issue, I released a new version 0.9.5 today which should make this message go away. If not, please let me know!
