### ISSUE TITLE
Setup failed for custom integration 'ssh': Unable to import component: cannot import name 'InvalidRequiredSensorError' from 'terminal_manager'

### ISSUE THREAD

**Issue by messageexplorer** [zhbjsh/homeassistant-ssh#32]
I have upgraded to HA Core 2024.12.1 and now I can see next error:

Logger: homeassistant.setup
Source: setup.py:334
First occurred: 11:34:20 (1 occurrences)
Last logged: 11:34:20

Setup failed for custom integration 'ssh': Unable to import component: cannot import name 'InvalidRequiredSensorError' from 'terminal_manager' (/usr/local/lib/python3.13/site-packages/terminal_manager/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ssh/__init__.py", line 8, in <module>
    from ssh_terminal_manager import (
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/ssh_terminal_manager/__init__.py", line 9, in <module>
    from terminal_manager import (
    ...<18 lines>...
    )
ImportError: cannot import name 'InvalidRequiredSensorError' from 'terminal_manager' (/usr/local/lib/python3.13/site-packages/terminal_manager/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1026, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ssh/__init__.py", line 8, in <module>
    from ssh_terminal_manager import (
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/ssh_terminal_manager/__init__.py", line 9, in <module>
    from terminal_manager import (
    ...<18 lines>...
    )
ImportError: cannot import name 'InvalidRequiredSensorError' from 'terminal_manager' (/usr/local/lib/python3.13/site-packages/terminal_manager/__init__.py)

**Comment by grego1981** [comment]
Same for me!

**Comment by zhbjsh** [comment]
Very sorry, I messed up the dependencies, please update to version 1.2.0 and let me know if everything works again!

**Comment by messageexplorer** [comment]
Hello,

Seems it is working now.

I replaced by another one at this moment. But Thank you for quick update.

**Comment by messageexplorer** [comment]
It is working now. Thank you for quick help.
